# docker-compose.yaml
version: "2"
services:
  WebProxy:
    image: traefik
    restart: always
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    networks:
      - local

  WebApp:
    image: candymi/cfweb:latest
    restart: always
    labels:
      - "traefik.port=8080"
      - "traefik.backend=WebApp"
      - "traefik.enable=true"
      - "traefik.domain=localhost"
      - "traefik.frontend.rule=Host:localhost"
    volumes:
      - ./script:/app/script/
    networks:
      - local

  WebDB:
    image: mysql:5.6 #支持8.X以上版本, 但是必须开启下面的COMMAND参数.
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=cfadmin
    # 8.x以上版本必须设置为mysql_native_password, 否则无法连接到MySQL
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      # 如需设置时区, 建议请将localtime提取到home目录下再挂在使用
      # - /etc/localtime:/etc/localtime
    ports:
      - 3306:3306
    networks:
      - local

networks:
  local:
    driver: bridge
