# docker-compose.yaml
version: "2"
services:
  WebApp:
    image: candymi/cfweb
    restart: always
    volumes:
      - ./script/:/app/script/
      # 如需设置时区, 建议请将localtime提取到home目录下再挂在使用
      # - /etc/localtime:/etc/localtime
    ports:
      - 8080:8080
    depends_on:
      - WebDB
    links:
      - WebDB:WebDB
    networks:
      - Web_Net

  WebDB:
    image: mysql:5.6 #支持8.X以上版本, 但是必须开启下面的COMMAND参数.
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=cfadmin
    # 8.x以上版本必须设置为mysql_native_password, 否则无法连接到MySQL
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      # 如需设置时区, 建议请将localtime提取到home目录下再挂在使用
      # - /etc/localtime:/etc/localtime
    ports:
      - 3306:3306
    networks:
      - Web_Net

networks:
  Web_Net:
    driver: bridge
